### ISSUE TITLE
Object [object Object] has no method '_getCollection'

### ISSUE THREAD

**Issue by buhrmi** [mikowals/batch-insert#1]
I really like this package and it's working fine locally. But as soon as the app is built and is deployed I run into this error whenever invoking SomeCollection.batchInsert(). Any hints would be really appreciated :o

**Comment by mikowals** [comment]
I think this will go away if you upgrade to version 1.1.7 with `meteor update mikowals:batch-insert`.  It was released a couple of days ago.   `_getCollection()` was the old way of accessing the mongo collection directly but it has gone away with Meteor 1.0.4.

If your problem persists let me know.  Thanks for the report.
