### ISSUE TITLE
batchInsert is undefined

### ISSUE THREAD

**Issue by bitomule** [mikowals/batch-insert#10]
I've added the package but it doesn't work. The only error report I get is that batchInsert is not defined. Last version is 1.1.13, that's what I have on my versions file. 

I've logged some collections and batchInsert function isn't defined.

**Comment by bitomule** [comment]
Seems like it was pulling something wrong, removed and added and works now.

**Comment by eugle** [comment]
Exception while invoking method 'database.restore.version' TypeError: Cannot read property 'batchInsert' of undefined

Same problem
