### ISSUE TITLE
How about batch updates?

### ISSUE THREAD

**Issue by sjmcdowall** [mikowals/batch-insert#11]
I have a meteor app where the server gets real-time streaming data feeds .. the first batch would be an insert, but from then on, it's all updates.  Is there an equivalent for that?  Also -- it's not exactly clear the advantage of this versus using a _.each() type loop to insert the documents .. just curious.  I am hoping to stop LiveQuery from going berserk with client updates (a bit at a time) and be more efficient. 

Cheers!

**Comment by Sivli-Embir** [comment]
+1 for an update option. As in you pass an array of arrays: [[query, setter], [query, setter]]. Also batch deletes would be nice. Maybe an array of ids?

Correct me if I am wrong but the benefit to this is much less network traffic. Rather then create a bunch of insert ddp calls. We call a single method which uploads the array. Is that correct?

**Comment by maxnowack** [comment]
+1

**Comment by vonrussel** [comment]
+1

**Comment by mikowals** [comment]
Implementing this has the same difficulties explained in #7.  Making bulk inserts easy is the scope of this package.  Updates are not in the scope.
