### ISSUE TITLE
Not respecting Collection2 schema

### ISSUE THREAD

**Issue by themeteorchef** [mikowals/batch-insert#18]
I'm running into an interesting issue (not sure if you'd call it a bug). I'm using collection2 to define a schema for documents, but it looks like batch insert is not being validated against the collection (like you might expect with a plain `Collection.insert()`). Is this expected?

The specific issue revolves around inserting an object with an incorrect property name via batch insert. For example, my schema has a field like `industryId`, however, if I insert an object with `industry` using Batch Insert, the object is still inserted. With a vanilla insert, I'd expect the field to get chopped off by collection2 or throw an error but that's not the case.

Any thoughts?

**Comment by mikowals** [comment]
batchInsert wraps the mongo driver insert and checks meteor core allow/deny rules.  It does not use the core Collection.insert function.

Changes to Collection.insert won't affect batchInsert behavior.  They are separate functions.

**Comment by aessig** [comment]
Is there any way of validating the data before insert when using batchInsert ?

**Comment by raza2022** [comment]
@mikowals Thanks for great work. is it possible to do same thing what other asked? or can you point the corner where i can inserted the field check method.
