### ISSUE TITLE
specifying unordered write operations

### ISSUE THREAD

**Issue by aon108** [mikowals/batch-insert#20]
Thanks for the great work on this functionality!

Im using ensureUnique on the collection, to prevent duplicate documents being inserted, rather than checking against every doc in the db.

Is there a way to specify `{ ordered: false }` as shown in [mongo bulk write docs](https://docs.mongodb.org/manual/core/bulk-write-operations/) so that the bulk insert will continue even if one insert fails?

I hope that was clear explanation. Looking forward to your response. thanks.

**Comment by mikowals** [comment]
I imagine this could be done in https://github.com/mikowals/batch-insert/blob/master/batch-insert-server.js#L129.  I considered this a long time ago.   I think when used this way the insert returns both an error and a result which gives you full information on which items were inserted and which failed.  That would not be consistent with the Meteor's `Collection.insert()` signature so I stopped considering it.

If you think other people will find this useful and it can be done without making the error and result handling change for most users, then I would encourage a pull request.  If it is just for you then forking and allowing the options you want is probably best.
