### ISSUE TITLE
batchInsert returns array of undefined values

### ISSUE THREAD

**Issue by ffxsam** [mikowals/batch-insert#22]
I have a batch insert operation that's just inserting two items into a collection:

``` js
const newIds = Records.batchInsert(oldItems);
```

Yet the value of `newIds` is:

``` js
[ undefined, undefined, undefined, undefined ]
```

**Comment by jonton11** [comment]
@ffxsam - I'm running into this same issue as well, did you ever figure out what was wrong?

**Comment by ffxsam** [comment]
Unfortunately not.

**Comment by mjwheatley** [comment]
I am also experiencing this issue.
I would like to add that I was doing a batch insert of 3 items, yet received an array containing 4 undefined values.

```
batch order insert result:  [ undefined, undefined, undefined, undefined ]
```

**Comment by mikowals** [comment]
fixed in package version 1.1.14 which was just published.

**Comment by jlichti** [comment]
Seeing this issue now after upgrading to Meteor 1.7.
Update - it kicked me back down to an old version of this package so I needed to clone locally and update the version constraints.

**Comment by fangjj** [comment]
Seeing this issue now after upgrading to METEOR@1.7.0.3

**Comment by jaybeemind** [comment]
Seeing this issue now with meteor @ 1.10.1
