### ISSUE TITLE
Problem to Insert

### ISSUE THREAD

**Issue by lionelromanelli** [mikowals/batch-insert#3]
Hi, I'm using the package as follows:

Items = new Meteor.Collection('items');
Items.allow({insert: function() {return true;}});
Items.batchInsert([{item: 1},{item: 2}]);

And I 'm getting the following error:

Exception while invoking method 'procesarCsvVentas' TypeError: Object [object Object] has no method 'rawCollection'
at [object Object].m.(anonymous function) (packages/mikowals:batch-insert/batch-insert.js:161:1)
at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
at packages/ddp/livedata_server.js:1513:1....

Can you help me?
Thanks!
Lionel.

**Comment by mikowals** [comment]
I think you are using a meteor version older than 1.0.4.  So either upgrade meteor or specify version 1.1.5 of this package.  Let me know if my assumptions are correct and if this suggestion works.

That you have to do this manually is my fault for not appropriately specifying Meteor version requirements for each package update.

**Comment by lionelromanelli** [comment]
You were right!. I update my Meteor version and this worked.
Thank you mikowals!

**Comment by mikowals** [comment]
Great!
