### ISSUE TITLE
Exception while invoking method - duplicate key error

### ISSUE THREAD

**Issue by Infinitism** [mikowals/batch-insert#30]
Hey, 

After I added this package and tried performing a batch insert on a method call inside a "Meteor.isServer" block, I get an error saying that insert failed because of documents having duplicate _id. I'm not assigning _id's anywhere and currently use SimpleSchema. 

I tried using this without attaching a schema to my collection and still have the issue. I have a deny rule for insert on the client and no allow insert because I want to modify the collection only on the server.

**Comment by Infinitism** [comment]
A work around for this issue would be to use `Random.id()` on the objects being inserted and use batch insert after. 

Example: `obj1 = { _id: Random.id() }`

An even faster way to get 1000s of data inserted (compared to this package) is simply using the raw collection. 

This is how I went about it. 
`try {
 let rawCollection = Cards.rawCollection();
rawCollection.insertMany([obj1, obj2 ..]);
} catch (e) {
console.log(e);
}
`
operations on raw collection returns a Promise. So if you'd like other operations to wait till they are done, just import Promise from the meteor package and change the code to

`Promise.await(rawCollection.insertMany([obj,obj]);`

This route makes operation faster and obviates the need for this package IMO.

**Comment by MrSpark2591** [comment]
i had similar issue with the code. what i found was i was looping over data and modifying same object and pushing it to array.

so code was something like this.

    var someobject = {
       p1: 1, 
       p2:2
     };
    var myArr = [];
    for(var i =0;i <3;i++){ 
      someobject.i = i; 
      myArr.push(someobject);
    }
     //than perfomingbatchinsert will throw same error. 

so i guess doing object deep cloning solves this.
