### ISSUE TITLE
Cannot read property 'batchInsert' of undefined

### ISSUE THREAD

**Issue by eugle** [mikowals/batch-insert#42]
meteor: 1.10.2
batch-insert: 1.2.0

Can't use，error: 
Exception while invoking method 'database.restore.version' TypeError: Cannot read property 'batchInsert' of undefined

**Comment by mikowals** [comment]
Thanks for reporting this.  Would you mind providing the code that produces this error?

**Comment by eugle** [comment]
Sorry, thank you for your quick reply, it's my fault, there is no problem

**Comment by mikowals** [comment]
Happy to hear it is working now.
