### ISSUE TITLE
Does this improve speed?

### ISSUE THREAD

**Issue by 0xpatrickdev** [mikowals/batch-insert#8]
Answer to this is probably extremely obvious, but would batch inserts improve performance?

If so, is it substantial? Thanks !

**Comment by mikowals** [comment]
Yes it improves performance in the app by making a single mongo request.  For 1000 docs using `batchInsert` took 300ms vs a loop which took 3000ms.  That is just checking time before the first db request and after the final insert completes.  

The measurement is very subjective so if it really matters to you I would try it in your app and monitor its performance.

**Comment by 0xpatrickdev** [comment]
Awesome, thank you @mikowals.  I am working with an API that only returns 20 items at a time, so I can only insert that many at a time.  I am assuming  I would get the same speed boost? (10x?) If so, that's awesome !

And what about upserts, does this work for that / have the same performance enhancements? 

Thanks !

**Comment by aessig** [comment]
I have the same question, how about upserts ? Can I do something with your package ? 
Cheers
